Repository shivammathur/homebrew-extensions, pull requests merged in 2021-10, with the labels that each got.

#1158 Update imap@8.2
  Formula/imap@8.2.rb
Labels: automated-pr, build-complete, CI-no-linux, imap@8.2

#1157 Update imap@8.1
  Formula/imap@8.1.rb
Labels: automated-pr, imap@8.1, build-complete, CI-no-linux

#1162 update xdebug@7.3
  Formula/xdebug@7.3.rb
Labels: build-complete

#1163 update xdebug@8.2
  Formula/xdebug@8.2.rb
Labels: build-complete

#1164 update xdebug@7.4
  Formula/xdebug@7.4.rb
Labels: build-complete
