Repository shivammathur/homebrew-extensions, pull requests merged in 2025-06, with the labels that each got.

#4880 gnupg@8.5 1.5.3
  Formula/gnupg@8.5.rb
Labels: build-complete

#4877 gnupg@8.2 1.5.3
  Formula/gnupg@8.2.rb
Labels: build-complete

#4870 gnupg@7.0 1.5.3
  Formula/gnupg@7.0.rb
Labels: build-complete

#4878 gnupg@8.3 1.5.3
  Formula/gnupg@8.3.rb
Labels: build-complete

#4874 gnupg@7.4 1.5.3
  Formula/gnupg@7.4.rb
Labels: build-complete

#4871 gnupg@7.1 1.5.3
  Formula/gnupg@7.1.rb
Labels: build-complete

#4884 snmp@8.4 8.4.8
  Formula/snmp@8.4.rb
Labels: build-complete

#4883 snmp@8.3 8.3.22
  Formula/snmp@8.3.rb
Labels: build-complete

#4882 imap@8.3 8.3.22
  Formula/imap@8.3.rb
Labels: build-complete

#4886 grpc@7.1 1.73.0
  Formula/grpc@7.1.rb
Labels: build-complete

#4892 grpc@8.2 1.73.0
  Formula/grpc@8.2.rb
Labels: build-complete

#4894 grpc@8.4 1.73.0
  Formula/grpc@8.4.rb
Labels: build-complete

#4888 grpc@7.3 1.73.0
  Formula/grpc@7.3.rb
Labels: build-complete

#4889 grpc@7.4 1.73.0
  Formula/grpc@7.4.rb
Labels: build-complete

#4895 grpc@8.5 1.73.0
  Formula/grpc@8.5.rb
Labels: build-complete

#4887 grpc@7.2 1.73.0
  Formula/grpc@7.2.rb
Labels: build-complete

#4897 Update snmp@8.5
  Formula/snmp@8.5.rb
Labels: automated-pr, build-complete, snmp@8.5

#4896 Update xdebug@8.5
  Formula/xdebug@8.5.rb
Labels: automated-pr, build-complete, xdebug@8.5

#4904 couchbase@8.2 4.3.0
  Formula/couchbase@8.2.rb
Labels: build-complete

#4906 couchbase@8.4 4.3.0
  Formula/couchbase@8.4.rb
Labels: build-complete

#4905 couchbase@8.3 4.3.0
  Formula/couchbase@8.3.rb
Labels: build-complete

#4907 couchbase@8.5 4.3.0
  Formula/couchbase@8.5.rb
Labels: build-complete

#4908 MongoDB 2.1.1
  Formula/mongodb@8.1.rb
  Formula/mongodb@8.2.rb
  Formula/mongodb@8.3.rb
  Formula/mongodb@8.4.rb
  Formula/mongodb@8.5.rb
Labels: build-complete

#4909 Update mongodb@1 to 1.21.1
  Formula/mongodb1@8.1.rb
  Formula/mongodb1@8.2.rb
  Formula/mongodb1@8.3.rb
  Formula/mongodb1@8.4.rb
  Formula/mongodb1@8.5.rb
Labels: build-complete

#4911 Update snmp@8.5
  Formula/snmp@8.5.rb
Labels: automated-pr, build-complete, snmp@8.5

#4913 Update snmp@8.5
  Formula/snmp@8.5.rb
Labels: automated-pr, build-complete, snmp@8.5

#4916 newrelic@8.0 11.10.0.24
  Formula/newrelic@8.0.rb
Labels: build-complete

#4915 newrelic@7.4 11.10.0.24
  Formula/newrelic@7.4.rb
Labels: build-complete

#4918 newrelic@8.2 11.10.0.24
  Formula/newrelic@8.2.rb
Labels: build-complete

#4920 newrelic@8.4 11.10.0.24
  Formula/newrelic@8.4.rb
Labels: build-complete

#4919 newrelic@8.3 11.10.0.24
  Formula/newrelic@8.3.rb
Labels: build-complete

#4917 newrelic@8.1 11.10.0.24
  Formula/newrelic@8.1.rb
Labels: build-complete

#4921 newrelic@7.4-11.10.0.24
  Formula/newrelic@7.4.rb
Labels: build-complete

#4922 newrelic@8.0-11.10.0.24
  Formula/newrelic@8.0.rb
Labels: build-complete

#4923 Update xdebug@8.5
  Formula/xdebug@8.5.rb
Labels: automated-pr, build-complete, xdebug@8.5
